### ISSUE TITLE
Error in get_signicant

### ISSUE THREAD

**Issue by gremame** [mildpiggy/DEP2#2]
Hello! I'm using **`DEP2 version 0.5.2.28`** and I have been getting an error when using the **`get_signicant`** function:

```
Error in get_signicant(object, contrast = manual_contrast) :
promise already under evaluation: recursive default argument reference or earlier problems?
```

Initially I thought it could be a problem with my data or that I wasn't using the function properly. However, I followed the [DEP2 analysis workflow](https://mildpiggy.github.io/DEP2/articles/03_DEP2_analysis.html) tutorial and got the same error when calling with **`get_signicant`** function with the data from the vignette.
Let me know if you need me to provide you with additional information regarding this issue.
Bests and congrats for the tool, I love how well documented everything is!

**Comment by mildpiggy** [comment]
Welcome to raise this issue, I apologize for taking so long to see and respond. This problem did indeed exist in the early versions of Version 0.5.2.28, and we fixed it in the last [commit ]((https://github.com/mildpiggy/DEP2/commit/e2cce58010876323546a2d54a93c426869b980bc). However, I cannot be entirely sure if the error you encountered was caused by the problem we fixed at that time.

If you installed DEP2 more than 3 weeks ago, I suggest you reinstall the latest version and try again, which theoretically should solve the error. But if you continue to encounter issues, I hope you can provide more data details.

**Comment by gremame** [comment]
Thanks for the update, I installed the latest version and now the `get_signicant` as well as the `plot_normalization` function are working with no issues. Thanks a lot! :muscle:
